### ISSUE TITLE
Find the Datasets .

### ISSUE THREAD

**Issue by Mavericks-club** [Mavericks-club/Handwritten-text-classification#4]
Collect data sets for the problem (try to get as much as possible atleast 8-10k images in same pixel format)

**Comment by CyberLogan** [comment]
hey assign me

**Comment by aman247av** [comment]
we can use MNIST dataset... it is almost used in building all the standard models

**Comment by aman247av** [comment]
my bad.. i was trying to suggest NIST dataset https://www.nist.gov/srd/nist-special-database-19. we can combine both dataset (NIST + MNIST)

**Comment by CyberLogan** [comment]
Nice one

**Comment by CyberLogan** [comment]
https://data.csafe.iastate.edu/HandwritingDatabase/
https://fki.tic.heia-fr.ch/databases/iam-handwriting-database
(For devnagri) https://www.isical.ac.in/~ujjwal/download/basiccharacter.html
